pubg_python/base.py
pubg_python/mixins.py

Fix redundant Accept-Encoding header

---

pubg_python/domain.py

Trying to understand the codebase...

Added comment for PC_KAKAO

---

README.md
pubg_python/mixins.py

Add multi filtering support

---

README.md

The playbattlegrounds official api documentation URL has been changed so the readme urls should be also updated.

Update readme URLs

---

pubg_python/clients.py

Added 'Bearer' prefix to api_key per documentation.

Add 'Bearer' prefix

---

README.md

Extend example "retrieving a list of players"

---

pubg_python/domain/base.py

Add map on match object attributes

---

README.md
pubg_python/domain/base.py

Update domain file links in readme, correctly map updatedAt field

---

README.md
pubg_python/base.py
pubg_python/domain/base.py
pubg_python/querysets.py

* Adds samples endpoint
* Adds usage documentation

Add samples endpoint

---

pubg_python/domain/telemetry/events.py

Fixed typo under LogPlayerAttack

---

pubg_python/domain/telemetry/events.py

I couldn't see any development branch. Bluehole released new telemetry events yesterday. I added them with this commit. If there is any question feel free to ask.

adds pubg latest telemetry events

---

CHANGELOG.md
pubg_python/domain/base.py
pubg_python/domain/telemetry/events.py
pubg_python/domain/telemetry/objects.py
setup.py

Add a few changes in API changelog

Changelog updates

---

CHANGELOG.md
README.md
pubg_python/base.py
pubg_python/domain/base.py
setup.py

* Add support for tournaments endpoint https://documentation.playbattlegrounds.com/en/tournaments-endpoint.html
Closes https://github.com/ramonsaraiva/pubg-python/issues/47

 Support tournaments data

---

pubg_python/domain/base.py

Fix failing build from flake8 issue

---

pubg_python/domain/telemetry/events.py

Tries to declare new Telemetry events

Add new API changes

---

pubg_python/domain/telemetry/events.py

Fix pep 8 2 blanks lines rule

---

.gitignore
pubg_python/domain/telemetry/events.py
tests/test_telemetryevents.py

Completed LogParachuteLanding event class.
Added unit tests for updated class

Telemetry parachute landing

---

CHANGELOG.md
pubg_python/domain/base.py
pubg_python/domain/telemetry/events.py
setup.py

Changelog sync

---

pubg_python/exceptions.py

:bug: fix unexpected response_headers in exceptions

---

.github/workflows/release.yml

Trigger release on published only

---

README.md
pubg_python/base.py
pubg_python/domain/base.py
tests/test_weapon_mastery.py
tests/weapon_mastery_response.json

✨ Add weapon mastery endpoint

---

pubg_python/domain/telemetry/events.py

Just added missing character and item objects in LogHeal

Added character and item used for healing
